Repository andela/apollo-ah-frontend, pull requests merged in 2019-04, with the labels that each got.

#2 #164198135 Set up empty react project
  .babelrc
  .eslintrc
  .gitignore
  package.json
  public/index.html
  src/index.jsx
  webpack.config.dev.js
  webpack.config.prod.js
Labels: ready

#5 #164198138 Set up react router
  .eslintrc
  package.json
  public/index.html
  src/components/HomePage.jsx
  src/index.jsx
  src/routes/index.jsx
  src/views/Login.jsx
  src/views/Signup.jsx
Labels: ready

#1 #164198138 Integrate circleci
  .circleci/config.yml
  README.md
Labels: ready

#3 #164198141 Integrate codeclimate test coverage
  .circleci/config.yml
  README.md
  package.json
Labels: WIP

#4 #164198136 Setup redux workflow
  .gitignore
  package.json
  src/actions/index.js
  src/constants/actionTypes.js
  src/index.jsx
  src/reducers/index.js
  src/reducers/sample.js
  src/store/index.js
  src/store/initialState.js
Labels: ready

#7 #165083375 Setup HoundCI
  .circleci/config.yml
  .hound.yml
  README.md
  package.json
  test/sample.test.js
Labels: ready

#6 #164198137 setup testing
  .circleci/config.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/sample_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/sample_spec.js.mp4
  package.json
  src/components/HomePage.jsx
  src/index.jsx
  src/routes/index.jsx
  src/test/components/Home.test.js
  test/sample.test.js
  webpack.config.dev.js
Labels: under-review

#10 #164198144 Users should be able to login to
  .babelrc
  .circleci/config.yml
  .eslintrc
  .gitignore
  .hound.yml
  cypress/videos/sample_spec.js.mp4
  enzyme.config.js
  package.json
  src/__mocks__/axios.js
  src/actions/actionTypeGenerator.js
  src/actions/articleCategoryAction.js
  src/actions/loginActions.js
  src/actions/typeGenerator.js
  src/components/HomePage.jsx
  src/components/Login.jsx
  src/images/Background.jpg
  src/index.jsx
  src/reducers/index.js
  src/reducers/loginReducers.js
  src/routes/index.jsx
  src/selectors/loginSelector.js
  src/store/index.js
  src/store/initialState.js
  src/styles/index.scss
  src/styles/login.scss
  src/styles/shared.scss
  src/test/__mocks__/mockLoginData.js
  src/test/actions/loginActions.test.js
  src/test/components/HomePage.test.js
  src/test/components/Login.test.js
  src/test/reducers/loginReducer.test.js
  src/test/views/AlertMessage.test.js
  src/test/views/UserForm.test.js
  src/utils/constants.js
  src/utils/finalRatings.js
  src/utils/getAverageRatings.js
  src/utils/inputValidator.js
  src/utils/time.js
  src/views/AlertMessage.jsx
  src/views/Articles.jsx
  src/views/Authors.jsx
  src/views/Body.jsx
  src/views/Category.jsx
  src/views/Navbar.jsx
  src/views/NotFound.jsx
  src/views/PageLoader.jsx
  src/views/UserForm.jsx
  src/views/placeholderLoader.jsx
  webpack.config.dev.js
Labels: WIP, implementing feedback

#8 #164198143 Users can reset password
  .eslintrc
  cypress/videos/sample_spec.js.mp4
  package.json
  src/actions/actionTypes.js
  src/actions/articleCategoryAction.js
  src/actions/index.js
  src/actions/modal.js
  src/actions/resetPassword.js
  src/actions/typeGenerator.js
  src/components/HomePage.jsx
  src/components/ResetPassword.jsx
  src/index.jsx
  src/reducers/index.js
  src/reducers/resetPasswordReducer.js
  src/reducers/sample.js
  src/routes/index.jsx
  src/selectors/resetPassword.js
  src/store/index.js
  src/styles/index.scss
  src/styles/login.scss
  src/styles/modal.scss
  src/styles/resetPassword.scss
  src/test/actions/resetPassAction.test.js
  src/test/components/Login.test.js
  src/test/components/Modal.test.js
  src/test/components/__snapshots__/Modal.test.js.snap
  src/test/reducers/resetPassReducer.test.js
  src/test/setup/index.jsx
  src/test/testUtilities/mockData.js
  src/test/testUtilities/store.js
  src/test/views/UserForm.test.js
  src/utils/request.js
  src/views/Modal.jsx
  src/views/UserForm.jsx
Labels: ready

#17 #165212485 Configure app for continuous deployment
  .env.example
  Procfile
  cypress/integration/sample_spec.js
  package.json
  serve
  webpack.config.dev.js
  webpack.config.prod.js
Labels: ready

#21 #165425357 Fix code climate test coverage
  .circleci/config.yml
  package.json
Labels: ready

#11 #164198145 Add support for social authentication
  assetsTransformer.js
  cypress/plugins/index.js
  cypress/support/index.js
  enzyme.config.js
  jest.config.js
  package.json
  src/actions/actionTypes.js
  src/actions/index.js
  src/actions/socialAction.js
  src/actions/typeGenerator.js
  src/components/SocialLogin.jsx
  src/images/icons/facebook.svg
  src/images/icons/google.svg
  src/images/icons/twitter.svg
  src/reducers/index.js
  src/reducers/loginReducers.js
  src/selectors/authSelector.js
  src/store/initialState.js
  src/styles/login.scss
  src/test/actions/loginActions.test.js
  src/test/actions/socialAction.test.js
  src/test/components/Articles.test.js
  src/test/components/Authors.test.js
  src/test/components/Category.test.js
  src/test/components/Footer.test.js
  src/test/components/HomePage.test.js
  src/test/components/Login.test.js
  src/test/components/Navbar.test.js
  src/test/components/SocialLogin.test.js
  src/test/components/__snapshots__/Articles.test.js.snap
  src/test/components/__snapshots__/Authors.test.js.snap
  src/test/components/__snapshots__/Category.test.js.snap
  src/test/components/__snapshots__/EditProfileContainer.test.js.snap
  src/test/components/__snapshots__/Footer.test.js.snap
  src/test/components/__snapshots__/HomePage.test.js.snap
  src/test/components/__snapshots__/Modal.test.js.snap
  src/test/components/__snapshots__/Navbar.test.js.snap
  src/test/components/__snapshots__/ProfileHeaderContainer.test.js.snap
  src/test/components/__snapshots__/SocialLogin.test.js.snap
  src/test/views/AlertMessage.test.js
  src/test/views/UserForm.test.js
  src/test/views/__snapshots__/EditProfile.test.js.snap
  src/test/views/__snapshots__/ProfileHeader.test.js.snap
  src/test/views/__snapshots__/Wrapper.test.js.snap
  src/test/views/common/SocialButton.test.js
  src/test/views/common/__snapshots__/SocialButton.test.js.snap
  src/utils/helpers.js
  src/views/UserForm.jsx
  src/views/common/SocialButton.jsx
  webpack.config.dev.js
  webpack.config.prod.js
Labels: ready

#22 #164198152 Implements display tags on relevant view
  package.json
  src/actions/resetPassword.js
  src/routes/ProtectedRoutes.jsx
  src/routes/index.jsx
  src/styles/singleArticle.scss
  src/test/components/Navbar.test.js
  src/test/components/__snapshots__/Navbar.test.js.snap
  src/test/selectors/navbarSelector.test.js
  src/test/utils/decodeToken.test.js
  src/test/views/ArticleBody.test.js
  src/test/views/ArticleTag.test.js
  src/test/views/EditProfile.test.js
  src/test/views/__snapshots__/ArticleBody.test.js.snap
  src/test/views/__snapshots__/ArticleTag.test.js.snap
  src/test/views/__snapshots__/EditProfile.test.js.snap
  src/views/ArticleBody.jsx
  src/views/ArticleTag.jsx
  src/views/ArticleTags.jsx
Labels: ready

#13 #164198147 Users can create articles
  package.json
  public/index.html
  src/actions/clearMessage.js
  src/actions/createArticles.js
  src/actions/loginActions.js
  src/actions/resetPassword.js
  src/components/CreateArticles.jsx
  src/components/ProfileHeaderContainer.jsx
  src/components/common/CloudinaryWidget.js
  src/images/icons/camera-icon-256-803400574.png
  src/images/icons/plus-icon-black.png
  src/images/icons/plus-icon-two.png
  src/images/icons/plus-icon.png
  src/index.jsx
  src/reducers/createArticleReducer.js
  src/reducers/index.js
  src/routes/ProtectedRoutes.jsx
  src/routes/index.jsx
  src/selectors/createArticleSelector.js
  src/store/index.js
  src/styles/index.scss
  src/styles/shared.scss
  src/styles/tags.scss
  src/test/actions/createArticle.js
  src/test/components/__snapshots__/Navbar.test.js.snap
  src/test/components/__snapshots__/createArticleContainer.test.js.snap
  src/test/components/createArticleContainer.test.js
  src/test/reducers/createArticleReducer.test.js
  src/test/setup/index.js
  src/test/views/__snapshots__/createArticle.test.js.snap
  src/test/views/createArticle.test.js
  src/utils/request.js
  src/views/CreateArticle.jsx
  src/views/Navbar.jsx
  src/views/TagsInput.jsx
  src/views/UserForm.jsx
Labels: ready

#15 #164198142 User signup
  .eslintrc
  cypress/integration/integration/sample_spec.js
  cypress/integration/sample_spec.js
  cypress/videos/sample_spec.js.mp4
  package.json
  src/actions/signupActions.js
  src/components/SignupForm.jsx
  src/reducers/articleReducer.js
  src/reducers/index.js
  src/reducers/signupReducer.js
  src/routes/index.jsx
  src/store/initialState.js
  src/styles/index.scss
  src/styles/shared.scss
  src/styles/signup.scss
  src/styles/variables.scss
  src/test/__mocks__/mockSignupData.js
  src/test/actions/signupAction.test.js
  src/test/components/ErrorAlert.test.js
  src/test/components/HomePage.test.js
  src/test/components/Input.test.js
  src/test/components/SignupForm.test.js
  src/test/components/SignupPage.test.js
  src/test/components/__snapshots__/ErrorAlert.test.js.snap
  src/test/components/__snapshots__/Input.test.js.snap
  src/test/components/__snapshots__/SignupForm.test.js.snap
  src/test/components/__snapshots__/SignupPage.test.js.snap
  src/test/reducers/acticleReducer.test.js
  src/test/reducers/signupReducer.test.js
  src/test/views/UserForm.test.js
  src/views/ErrorAlert.jsx
  src/views/Input.jsx
  src/views/SignupPage.jsx
Labels: ready

#23 #164198149 Implements view and post comments for an article
  enzyme.config.js
  src/actions/commentsAction.js
  src/actions/createArticles.js
  src/components/Article.jsx
  src/components/CommentsContainer.jsx
  src/components/EditProfileContainer.jsx
  src/reducers/commentsReducer.js
  src/reducers/index.js
  src/selectors/commentsSelector.js
  src/store/initialState.js
  src/styles/article.scss
  src/styles/comments.scss
  src/styles/index.scss
  src/styles/singleArticle.scss
  src/styles/variables.scss
  src/test/actions/commentsAction.test.js
  src/test/components/CommentsContainer.test.js
  src/test/components/__snapshots__/CommentsContainer.test.js.snap
  src/test/components/__snapshots__/EditProfileContainer.test.js.snap
  src/test/components/__snapshots__/ProfileHeaderContainer.test.js.snap
  src/test/reducers/commentReducer.test.js
  src/test/selectors/commentsSelectors.test.js
  src/test/setup/index.js
  src/test/views/CommentBox.test.js
  src/test/views/CommentForm.test.js
  src/test/views/CommentLoader.test.js
  src/test/views/__snapshots__/ArticleBody.test.js.snap
  src/test/views/__snapshots__/CommentBox.test.js.snap
  src/test/views/__snapshots__/CommentForm.test.js.snap
  src/test/views/__snapshots__/CommentLoader.test.js.snap
  src/test/views/__snapshots__/EditProfile.test.js.snap
  src/test/views/__snapshots__/ProfileHeader.test.js.snap
  src/utils/helpers.js
  src/views/ArticleBody.jsx
  src/views/CommentBox.jsx
  src/views/CommentForm.jsx
  src/views/CommentLoader.jsx
Labels: ready

#24 #164198150 Pagination component
  package.json
  src/__mocks__/axios.js
  src/__mocks__/fileMock.js
  src/actions/articleAction.js
  src/components/HomePage.jsx
  src/components/Pagination.jsx
  src/components/ResetPassword.jsx
  src/reducers/articleReducer.js
  src/styles/index.scss
  src/styles/pagination.scss
  src/test/actions/articleAction.test.js
  src/test/components/HomePage.test.js
  src/test/components/Pagination.test.js
  src/test/components/__snapshots__/Pagination.test.js.snap
  src/test/reducers/acticleReducer.test.js
  src/test/reducers/loginReducer.test.js
  src/test/setup/index.js
  src/views/Body.jsx
  src/views/UserForm.jsx
Labels: ready

#28 #165578239 implement 404 page
  src/components/NotFound.jsx
  src/routes/index.jsx
  src/selectors/singleArticleSelector.js
  src/styles/404.scss
  src/styles/article.scss
  src/styles/index.scss
  src/styles/variables.scss
  src/test/components/NotFound.test.js
  src/test/components/__snapshots__/NotFound.test.js.snap
  src/test/setup/index.js
  src/test/views/AlertMessage.test.js
  src/test/views/PageLoader.test.js
  src/test/views/__snapshots__/PageLoader.test.js.snap
  src/views/NotFound.jsx
Labels: ready

#25 #165343408 modify read-article page
  jest.config.js
  package.json
  public/index.html
  src/actions/bookmarkActions.js
  src/actions/singleArticleActions.js
  src/components/Article.jsx
  src/components/HomePage.jsx
  src/components/Login.jsx
  src/components/ResetPassword.jsx
  src/reducers/bookmarkArticleReducer.js
  src/reducers/index.js
  src/reducers/loginReducers.js
  src/reducers/singleArticleReducer.js
  src/routes/index.jsx
  src/selectors/bookmarkSelector.js
  src/selectors/loginSelector.js
  src/store/initialState.js
  src/styles/article.scss
  src/styles/shared.scss
  src/styles/singleArticle.scss
  src/test/__mocks__/mockLoginData.js
  src/test/__mocks__/mockSingleArticleData.js
  src/test/actions/bookmarkArticleAction.test.js
  src/test/actions/singleArticleActions.test.js
  src/test/components/Login.test.js
  src/test/components/SingleArticle.test.js
  src/test/components/__snapshots__/Articles.test.js.snap
  src/test/components/__snapshots__/Login.test.js.snap
  src/test/components/__snapshots__/NotFound.test.js.snap
  src/test/components/__snapshots__/SingleArticle.test.js.snap
  src/test/reducers/bookmarkArticlesReducer.test.js
  src/test/reducers/loginReducer.test.js
  src/test/reducers/singleArticleReducer.test.js
  src/test/setup/index.js
  src/test/views/ArticleBody.test.js
  src/test/views/DummyArticleLoader.test.js
  src/test/views/UserForm.test.js
  src/test/views/__snapshots__/ArticleBody.test.js.snap
  src/test/views/__snapshots__/DummyArticleLoader.test.js.snap
  src/utils/debounce.js
  src/utils/request.js
  src/views/ArticleBody.jsx
  src/views/Articles.jsx
  src/views/DummyArticleLoader.jsx
  src/views/ScrollToTopOnMount.jsx
  src/views/UserForm.jsx
Labels: ready

#34 #165665636 Resolve jest memory usage on CircleCI
  package.json
Labels: bug, ready

#20 #165250447 Article categories
  .eslintrc
  src/components/HomePage.test.tsx
  src/services/http.js
  src/test/components/__snapshots__/SingleArticle.test.js.snap
  src/test/views/__snapshots__/ArticleBody.test.js.snap
  src/views/Navbar.jsx
  src/views/index.jsx
  webpack.config.dev.js
  webpack.config.prod.js
Labels: ready

#26 #165344089 Add support for clapping articles
  package.json
  public/index.html
  src/actions/clapsAction.js
  src/components/ClapButton.jsx
  src/reducers/articleReducer.js
  src/reducers/clapsReducer.js
  src/reducers/index.js
  src/reducers/singleArticleReducer.js
  src/selectors/authSelector.js
  src/selectors/clapsSelector.js
  src/selectors/singleArticleSelector.js
  src/store/initialState.js
  src/styles/singleArticle.scss
  src/test/actions/clapsAction.test.js
  src/test/components/ClapButton.test.js
  src/test/components/__snapshots__/ClapButton.test.js.snap
  src/test/components/__snapshots__/SingleArticle.test.js.snap
  src/test/reducers/clapsReducer.test.js
  src/test/reducers/singleArticleReducer.test.js
  src/test/selectors/clapsSelector.test.js
  src/test/setup/index.js
  src/test/views/__snapshots__/ArticleBody.test.js.snap
  src/utils/contants.js
  src/utils/request.js
  src/views/ArticleBody.jsx
Labels: ready
